# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: OpenBikeSensor
email: info@openbikesensor.org
description: >-
  Home of the open source, open data and citizen science project
  OpenBikeSensor.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: OpenBikeSensor
github_username: openbikesensor

exclude:
   - Gemfile
   - Gemfile.lock
   - vendor

# Theme
remote_theme: pmarsceill/just-the-docs

# Theme "Just the docs" settings
logo: "/assets/images/logo_400x400.png"
search_enabled: true

aux_links:
  "GitHub":
    - "//github.com/openbikesensor"
  "Twitter":
    - "//twitter.com/openbikesensor"
  "Slack":
    - "/slack"

aux_links_new_tab: true
heading_anchors: true

## Footer

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

## Color
color_scheme: obs
#color_scheme: dark

# Github config
# markdown: GFM

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: Edit this page on GitHub.
gh_edit_repository: "https://github.com/openbikesensor/openbikesensor.github.io" # the github URL for your repo
gh_edit_branch: master # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: edit # "tree" or "edit" if you want the user to jump into the editor immediately
